#
# Makefile
#

apkg_cmd = /usr/local/libexec/arisia/bin/apkg

all:
	if [ -f $(apkg_cmd) ] ; then \
		$(apkg_cmd) button.jspkg ; \
		$(apkg_cmd) checkbox.jspkg ; \
		$(apkg_cmd) hello.jspkg ; \
		$(apkg_cmd) label.jspkg ; \
		$(apkg_cmd) icon.jspkg ; \
		$(apkg_cmd) image.jspkg ; \
		$(apkg_cmd) iife.jspkg ; \
		$(apkg_cmd) list-view.jspkg ; \
		$(apkg_cmd) open-url.jspkg ; \
		$(apkg_cmd) panel.jspkg ; \
		$(apkg_cmd) proc-0.jspkg ; \
		$(apkg_cmd) popup-menu.jspkg ; \
		$(apkg_cmd) radio-buttons.jspkg ; \
		$(apkg_cmd) shell.jspkg ; \
		$(apkg_cmd) sprite.jspkg ; \
		$(apkg_cmd) stepper.jspkg ; \
		$(apkg_cmd) table-data-0.jspkg ; \
		$(apkg_cmd) table-view-0.jspkg ; \
		$(apkg_cmd) textfield.jspkg ; \
		$(apkg_cmd) textedit.jspkg ; \
		$(apkg_cmd) terminal.jspkg ; \
		$(apkg_cmd) console-view.jspkg ; \
		$(apkg_cmd) console-view2.jspkg ; \
		$(apkg_cmd) timer.jspkg ; \
		$(apkg_cmd) resource.jspkg ; \
	fi
	(cd button.jspkg && make)
	(cd checkbox.jspkg && make)
	(cd hello.jspkg && make)
	(cd label.jspkg && make)
	(cd icon.jspkg && make)
	(cd iife.jspkg && make)
	(cd image.jspkg && make)
	(cd list-view.jspkg && make)
	(cd open-url.jspkg && make)
	(cd panel.jspkg && make)
	(cd proc-0.jspkg && make)
	(cd popup-menu.jspkg && make)
	(cd radio-buttons.jspkg && make)
	(cd shell.jspkg && make)
	(cd sprite.jspkg && make)
	(cd stepper.jspkg && make)
	(cd table-data-0.jspkg && make)
	(cd table-view-0.jspkg && make)
	(cd textedit.jspkg && make)
	(cd textfield.jspkg && make)
	(cd terminal.jspkg && make)
	(cd console-view.jspkg && make)
	(cd console-view2.jspkg && make)
	(cd timer.jspkg && make)
	(cd resource.jspkg && make)

clean:
	(cd hello.jspkg && make clean)
	(cd label.jspkg && make clean)
	(cd icon.jspkg && make clean)
	(cd image.jspkg && make clean)
	(cd list-view.jspkg && make clean)
	(cd open-url.jspkg && make clean)
	(cd popup-menu.jspkg && make clean)
	(cd radio-buttons.jspkg && make clean)
	(cd shell.jspkg && make clean)
	(cd sprite.jspkg && make clean)
	(cd stepper.jspkg && make clean)
	(cd textedit.jspkg && make clean)
	(cd textfield.jspkg && make clean)
	(cd table-data-0.jspkg && make clean)
	(cd table-view-0.jspkg && make clean)
	(cd terminal.jspkg && make clean)
	(cd console-view.jspkg && make clean)
	(cd console-view2.jspkg && make clean)
	(cd timer.jspkg && make clean)
	(cd resource.jspkg && make clean)

