#
# Makefile
#

root_dir = ..
include ../Makefile.inc

srcs	= Button.md4 \
	  Box.md4 \
	  CheckBox.md4 \
	  Collection.md4 \
	  Console.md4 \
	  IconView.md4 \
	  Image.md4 \
	  Label.md4 \
	  ListView.md4 \
	  Properties.md4 \
	  PopupMenu.md4 \
	  RadioButtons.md4 \
	  Shell.md4 \
	  Sprite.md4 \
	  Stepper.md4 \
	  TableData.md4 \
	  TableView.md4 \
	  TextEdit.md4 \
	  TextField.md4 \
	  Timer.md4
dsts	= $(srcs:.md4=.md)

all: $(dsts)

clean:
	rm -f $(dsts)


